version: '3'

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.7
    restart: always
    volumes:
      - ./apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "19000:9000"
    networks:
      apisix:

  apisix:
    image: apache/apisix:2.7-alpine
    restart: always
    volumes:
      - ./logs/apisix:/usr/local/apisix/logs
      - ./apisix/static:/usr/local/apisix/static
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/plugins/access-auth.lua:/usr/local/apisix/apisix/plugins/access-auth.lua
      - ./apisix/plugins/oss-proxy.lua:/usr/local/apisix/apisix/plugins/oss-proxy.lua
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "19090:9090/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    user: root
    restart: always
    volumes:
      - ./etcd/data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
