versiong: '3'

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.7
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      apisix:

  apisix:
    build:
      context: ./apisix
    volumes:
      - ./logs/apisix:/usr/local/apisix/logs
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9090:9090/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    user: root
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
